config/routes.rb
Rails.application.routes.draw do
  root "characters#index"

  get "signup" => "users#new"

  resources :users
  resources :characters

  get "signin" => "sessions#new"
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters, dependent: :destroy

  has_secure_password
  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 10, allow_blank: true }
  validates :username, presence: true, format: { with: /\A[A-Z0-9]+\z/i }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in first"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def current_user?(user)
    current_user == user
  end
  helper_method :current_user?

  def current_user_admin?
    current_user&.admin?
  end
  helper_method :current_user_admin?

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :require_signin, only: %i[ new edit create update destroy]
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    if current_user_admin?
      @characters = Character.all
    elsif current_user
      @characters = Character.where(user_id: current_user.id)
    else
      @characters = []
    end
  end

  # GET /characters/1 or /characters/1.json
  def show
    not_found unless user_can_access_character
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
    not_found unless user_can_access_character
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)
    @character.user = current_user

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_character
    @character = Character.find(params[:id])
  end

  def user_can_access_character
    current_user_admin? || current_user&.id == @character.user_id
  end

  # Only allow a list of trusted parameters through.
  def character_params
    params.require(:character).permit(:name, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user =
      User.find_by(email: params[:email_or_username]) ||
      User.find_by(username: params[:email_or_username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user), notice: "Welcome back, #{user.name}"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to characters_url, notice: "You're now signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to characters_url, alert: "Account successfully deleted"
  end

  private

  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation, :username)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_creation_form.html.erb
<%= form_with(model: character) do |form| %>
  <div class="field">
    Step: <%= character.creation_step %>
    <%= form.label :str, class: "formlabel" %>
    <%= character.str %>

    <%= form.label :dex, class: "formlabel" %>
    <%= character.dex %>

    <%= form.label :con, class: "formlabel" %>
    <%= character.con %>

    <%= form.label :int, class: "formlabel" %>
    <%= character.int %>

    <%= form.label :wis, class: "formlabel" %>
    <%= character.wis %>

    <%= form.label :chr, class: "formlabel" %>
    <%= character.chr %>
  </div>
<% end %>

app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "formLabel" %>
    <%= form.text_field :name, class: "formField" %>
    <%= form.submit :class => "cta_button" %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>
<%= render 'creation_form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<div class="card-container">
  <% if @characters.any? %>
    <% @characters.each do |character| %>
      <div class="card-body">
        <p class="card-image"><img src="https://picsum.photos/200"></p>
        <%= character.name %>
        <% if current_user_admin? %>
          <p>
            User: <%= character.user.name %>
          </p>
        <% end %>
        <p class="card-info">more information in this tag<br>and then theres more<br>perhaps a bit more</p>
        <div class="button-container">
          <%= link_to 'Show', character, :method => "get", :class => "card-button" %>
          <%= link_to 'Edit', edit_character_path(character), :method => "get", :class => "card-button" %>
          <%= link_to 'Delete', character, method: :delete, data: { confirm: 'Are you sure?' }, :class => "card-button" %>
        </div>
      </div>
    <% end %>
  <% elsif current_user %>
    <p>
      It appears you haven't made any characters yet.
      You can create your first character by clicking on New Character
    </p>
  <% else %>
    <p>
      It appears you're not signed in. Please sign in to create characters
    </p>
  <% end %>
</div>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/_header.html.erb
<header class = "navBar">
  <nav>
    <ul>
      <li class="navItem">CharGen</li>
      <% if current_user %>
        <li><%= link_to 'New Character', new_character_path, class: "navItem" %></li>
        <li><%= link_to "Existing Characters", characters_path, class: "navItem"%></li>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropbtn">User Profile</a>
            <div class="dropdown-content">
              <%= link_to current_user.name, current_user, class: "navItem" %>
              <%= link_to "Account Settings", edit_user_path(current_user), class: "navItem" %>
              <%= link_to "Sign Out", session_path, method: :delete, class: "navItem" %>
            </div>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", signin_path, class: "navItem" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "navItem" %>
        </li>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChargenRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any?  %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <% if current_user %>
      <h1>Edit Account</h1>
    <% else %>
      <h1>Sign Up</h1>
    <% end %>

    <%= f.label :name, class: "formLabel" %>
    <%= f.text_field :name, autofocus: true, class: "formField" %>

    <%= f.label :email, class: "formLabel"  %>
    <%= f.email_field :email, class: "formField" %>

    <%= f.label :username, class: "formLabel"  %>
    <%= f.text_field :username, placeholder: "Alphanumeric characters only", class: "formField" %>

    <%= f.label :password, class: "formLabel"  %>
    <%= f.password_field :password, class: "formField" %>

    <%= f.label :password_confirmation, "Confirm Password", class: "formLabel"  %>
    <%= f.password_field :password_confirmation, class: "formField" %>

    <div class="actions">
      <% if user.new_record? %>
        <%= f.submit "Create Account", :class => "cta_button" %>
      <% else %>
        <%= f.submit "Update Account", :class => "cta_button" %>
      <% end %>
      </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul>
  <% @users.each do |user| %>
  <li>
    <%= link_to user.name, user %>
    created
    <%= time_ago_in_words(user.created_at) %> ago
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= render "form", user: @user %>

app/views/users/show.html.erb
<section>
  <div class="field">
  <h1>User Account Information</h1>
  <div class="displayInfo">Name: <%= @user.name %></div>
  <div class="displayInfo">Email: <%= mail_to(@user.email) %></div>
  <div class="displayInfo">User Name: <%= @user.username %></div>

  <% if current_user?(@user) %>
    <div class="actions">
      <%= link_to 'Edit Account', edit_user_path(@user), :class => "formButton" %>
      <%= link_to 'Delete Account', @user, method: :delete, :class => "formButton", 
                  data: { confirm: "Permanently delete your account?" } %>
    </div>
  <% end %>
  </div>
</section>